version: '2'

networks:
    monitor:
        driver: bridge

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        restart: always
        volumes:
            - /c/www/WOS_CORE/src/runing/pro/prometheus.yml:/etc/prometheus/prometheus.yml
            - /c/www/WOS_CORE/src/runing/pro/node_down.yml:/etc/prometheus/node_down.yml
        ports:
            - "9090:9090"
        networks:
            - monitor

    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        hostname: alertmanager
        restart: always
        volumes:
            - /c/www/WOS_CORE/src/runing/pro/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        ports:
            - "9093:9093"
        networks:
            - monitor

    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        ports:
            - "3000:3000"
        networks:
            - monitor

    node-exporter:
        image: quay.io/prometheus/node-exporter
        container_name: node-exporter
        hostname: node-exporter
        restart: always
        ports:
            - "9100:9100"
        networks:
            - monitor

    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        hostname: cadvisor
        restart: always
        volumes:
            - /c/www/WOS_CORE/src/runing/pro:/rootfs:ro
            - /c/www/WOS_CORE/src/runing/pro:/var/run:rw
            - /c/www/WOS_CORE/src/runing/pro:/sys:ro
            - /c/www/WOS_CORE/src/runing/pro:/var/lib/docker:ro
        ports:
            - "8080:8080"
        networks:
            - monitor