// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: bas.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_bas_proto protoreflect.FileDescriptor

var file_bas_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x32,
	0x05, 0x0a, 0x03, 0x42, 0x61, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_bas_proto_goTypes = []interface{}{}
var file_bas_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bas_proto_init() }
func file_bas_proto_init() {
	if File_bas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bas_proto_goTypes,
		DependencyIndexes: file_bas_proto_depIdxs,
	}.Build()
	File_bas_proto = out.File
	file_bas_proto_rawDesc = nil
	file_bas_proto_goTypes = nil
	file_bas_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BasClient is the client API for Bas service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BasClient interface {
}

type basClient struct {
	cc grpc.ClientConnInterface
}

func NewBasClient(cc grpc.ClientConnInterface) BasClient {
	return &basClient{cc}
}

// BasServer is the server API for Bas service.
type BasServer interface {
}

// UnimplementedBasServer can be embedded to have forward compatible implementations.
type UnimplementedBasServer struct {
}

func RegisterBasServer(s *grpc.Server, srv BasServer) {
	s.RegisterService(&_Bas_serviceDesc, srv)
}

var _Bas_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Bas",
	HandlerType: (*BasServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "bas.proto",
}
